"""empty message

Revision ID: 00e854de543f
Revises: 67f7ff6b2099
Create Date: 2021-11-23 15:27:23.941502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e854de543f'
down_revision = '67f7ff6b2099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_control', 'change_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_control', sa.Column('change_number', sa.VARCHAR(length=32), nullable=True))
    # ### end Alembic commands ###
