"""empty message

Revision ID: 67f7ff6b2099
Revises: 
Create Date: 2021-10-31 15:12:51.340111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67f7ff6b2099'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_control', sa.Column('change_number', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_control', 'change_number')
    # ### end Alembic commands ###
